name: Docker Image CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Docker Build
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/scraper:${{ github.sha }}
    - name: Docker push
      run: docker push scraper:${{ github.sha }}

