name: Docker Image CI

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_TAG: ${{secrets.DOCKER_USERNAME}/scraper:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      run: docker login -u $DOCKER_USER  -p $DOCKER_PASSWORD 
    - name: Docker Build
      run: docker build . --file Dockerfile --tag $DOCKER_TAG
    - name: Docker push
      run: docker push $DOCKER_TAG

