name: Docker Image CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker build . --file Dockerfile --tag gold7777:scraper:${{ github.sha }}
    - name: Docker push
      run: docker push gold7777:scraper:${{ github.sha }}

